const ERROR_CODES = {
    VALIDATION_ERROR: "VALIDATION_ERROR",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
    DATABASE_ERROR: "DATABASE_ERROR",
    FILE_UPLOAD_ERROR: "FILE_UPLOAD_ERROR",
    CLOUDINARY_ERROR: "CLOUDINARY_ERROR",
    AI_SERVICE_ERROR: "AI_SERVICE_ERROR",
    DUPLICATE_COMPLAINT: "DUPLICATE_COMPLAINT",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
};

export default ERROR_CODES;