services:
  - type: web
    name: jansamadhan-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://janasamadhan-ai.netlify.app
      - key: AI_SERVER_URL
        value: https://prafulll-janasamadhan-ai-service.hf.space/api/v1
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
